<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if ($posts = $this->getRecent()): ?>
  <div class="collapsible mobile-collapsible">

        <h3 class="block-title heading"><?php echo Mage::helper('blog')->__('Latest News'); ?><span class="accordion-footer visible-xs">accordion-footer</span></h3>
        <div class="block-content block-content-statick">
        <ul class="bullet">
            <?php foreach ($posts as $post): ?>
                <li><em class="fa fa-angle-right">&nbsp;</em><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></li>
            <?php endforeach; ?>
        </ul>
        </div>
  </div>
<?php endif; ?>