<?php
$theme = $this->helper('mtbelano');
$equalHeight = $theme->getCfg('category_grid/equal_height');
$displayAddtocart = $theme->getCfg('category_grid/display_addtocart');
$displayAddtolink = $theme->getCfg('category_grid/display_addtolinks');
$compareHeader = $theme->getCfg('header/compare');
?>
<script type="text/javascript">
    <?php if ($equalHeight): ?>
    function setGridItemsEqualHeight($)
    {
        var winWidth = $(window).width();
        var SPACING = 20;
        if (winWidth >= 480)
        {
            $('.show-grid').removeClass("auto-height");
            var gridItemMaxHeight = 0;
            $('.show-grid > .item').each(function() {
                $(this).css("height", "auto");
                <?php if ($displayAddtocart == 2 || $displayAddtolink == 2): ?>
                var actionsHeight = $(this).find('.actions').height();
                $(this).css("padding-bottom", (actionsHeight + SPACING) + "px"); //Set new padding
                <?php endif; ?>
                gridItemMaxHeight = Math.max(gridItemMaxHeight, $(this).height());
            });
            $('.show-grid > .item').css("height", gridItemMaxHeight + "px");
        }
        else
        {
            $('.show-grid').addClass("auto-height");
            $('.show-grid > .item').css("height", "auto");
            $('.show-grid > .item').css("padding-bottom", "20px");
        }
    }
    <?php endif; ?>
    function setGridItem($){
        var winWidth = $(window).width();
        var col = <?php echo $theme->getCfg('category_grid/column_count');?>;
        if(winWidth > 768){
            newcol = col;
        }
        if(winWidth < 768 && winWidth >=640){
            newcol = <?php echo $theme->getCfg('category_grid/column_count_768');?>;
        }
        if(winWidth >=480 && winWidth <640){
            newcol = <?php echo $theme->getCfg('category_grid/column_count_640');?>;
        }
        if(winWidth < 480){
            newcol = <?php echo $theme->getCfg('category_grid/column_count_480');?>;
        }
        $i = 0;
        $('.show-grid > .item').each(function() {
            $i++;
            $(this).removeClass('first');
            $(this).removeClass('last');
            if(($i-1)%newcol==0){
                $(this).addClass('first');
            }else if($i%newcol==0){
                $(this).addClass('last');
            }
        });
    }
    $mt(function($) {
        var winWidth = $(window).width();
        var winHeight = $(window).height();
        var windowResize_t;
        $(window).resize(function() {
            var winNewWidth = $(window).width();
            var winNewHeight = $(window).height();
            if (winWidth != winNewWidth || winHeight != winNewHeight)
            {
                clearTimeout(windowResize_t);
                windowResize_t = setTimeout(function() {
                    $(document).trigger("themeResize");
                    <?php if ($equalHeight): ?>
                    setGridItemsEqualHeight($);
                    <?php endif; ?>
                    setGridItem($);
                }, 200);
            }
            winWidth = winNewWidth;
            winHeight = winNewHeight;
        });
        <?php if($compareHeader):?>
        $('.mt-maincompare').hover(
            function () {
                $(this).addClass('compare-active').find('.mtajaxcompare').stop().delay(200).slideDown();
            },
            function () {
                $(this).removeClass('compare-active').find('.mtajaxcompare').stop().delay(200).slideUp();
            }
        );
        <?php endif; ?> 
        $("#select-language").selectbox();
        $("#select-currency").selectbox();
		//lazyload
        $("img.lazy").lazy({
            effect : "fadeIn",
            effectTime: 800,
            threshold: 50, 
            afterLoad: function(element) {
                <?php if ($equalHeight): ?>
				setGridItemsEqualHeight($);
				<?php endif; ?>
            }
        });
		//Back to top
			$(window).scroll(function () {
				if ($(this).scrollTop() > 100) {
					$('#back-top').fadeIn();
				} else {
					$('#back-top').fadeOut();
				}
			});
			$('#back-top a').click(function () {
				$('body,html').animate({
					scrollTop: 0
				}, 800);
				return false;
			});
    });
    $mt(window).load(function(){
        <?php if ($equalHeight): ?>
        setGridItemsEqualHeight($mt);
        <?php endif; ?>
        setGridItem($mt);
    });
	// JavaScript Document
    $mt(document).ready(function(){
        $mt("[rel=tooltip]").tooltip();
        
         //DatePicker
        $mt('.input-group.date').datepicker({
			format: "dd/mm/yyyy",
			orientation: "auto left",
			autoclose: true
			});
			//stop it from hiding on select
			$mt('.input-group.date').on('hide', function (e) { e.preventDefault(); });
    });
   
	$mt(".accordion-footer").addClass("accordion-show");
        $mt(".accordion-footer").click(function(){
            if($mt(this).parent().next().is(":visible")){
                $mt(this).addClass("accordion-show");
            }else{
                $mt(this).removeClass("accordion-show");
            }
            $mt(this).parent().next().toggle(400);
        });
</script>