<div class="row">
    <div class="col-md-12">
        <p class="lead">Our Package Deals are designed to make the process of buying a new custom printed tent as easy as possible! Every printed panel that you see in each package comes with<strong> <span style="text-decoration: underline;">UNLIMITED</span></strong> printing and unlimited colors! If you like one of these packages all you need to decide on is the frame range you want to go for - click the Frame Options tab above for more information on our Pro Expo, Trader and Steel Sport Series frames.&nbsp;</p>
        <p><strong>Found a package you like? </strong><br />1. Click on the FREE Visual tab above<br />2. Fill out your contact details<br />3. Select the package you're interested in<br />4. Upload your logos, click Submit</p>
        <p>....and we'll do the rest! Within 24hrs a member of our Sales Team will contact you with your visual and an itemised quote that provides you with prices in each of our three frame ranges.</p>
        <hr />
    </div>
    <div class="col-md-3"><!-- Nav tabs -->
        <ul class="nav nav-tabs nav-stacked stacked">
            <li class="active"><a href="#basic-digital" data-toggle="tab">Basic Digital Package</a></li>
            <li><a href="#full-digital" data-toggle="tab">Full Digital Print Package</a></li>
            <li><a href="#trader-b" data-toggle="tab">Trader Digital Package</a></li>
            <li><a href="#sport-digital-extreme" data-toggle="tab">Sport Digital Package</a></li>
            <li><a href="#expo-digital" data-toggle="tab">Expo Digital Package</a></li>
            <li><a href="#instant-event" data-toggle="tab">Instant Event Package</a></li>
            <li><a href="#instant-exhibition" data-toggle="tab">Instant Exhibition Package</a></li>
            <li><a href="#instant-trader" data-toggle="tab">Instant Trader Package</a></li>
        </ul>
    </div>
    <div class="col-md-9"><!-- Tab panes -->
        <div class="tab-content stacked-tabs">
            <div id="basic-digital" class="tab-pane active">
                <div class="row">
                    <div class="col-md-5">
                        <h2 class="top-m-0 header-stroke"><span>Basic Digital Package<br /></span></h2>
                        <ul class="featured">
                            <li>Sublimation printed top</li>
                            <li>Unlimited print coverage!</li>
                            <li>Great value discounted package deal</li>
                            <li>Complete with Roller Wheel Bag</li>
                            <li>Tie down ropes and stakes kit</li>
                            <li>2 or 3 year warranty depending on frame choice</li>
                            <li class="thumb-li">600 Denier PVC backed materials</li>
                            <li class="thumb-li">100% Waterproof &amp; Flameproof</li>
                            <li class="thumb-li">12 month UV anti-fade guarantee<br /><br /></li>
                            <li class="thumb-li"><span style="font-size: medium;"><a href="/basic-digital-package.html" target="_self">Click here for more information</a></span></li>
                        </ul>
                    </div>
                        <div class="col-md-7 tab-pane active" id="basic-10-10"><a href="/basic-digital-package.html" target="_self"><img class="img-responsive" src="{{skin url='images/packages/basic-digital.jpg'}}" alt="" /></a></div>

                </div>
            </div>
            <div id="full-digital" class="tab-pane fade">
                <div class="row">

                    <div class="col-md-5">
                        <h2 class="top-m-0 header-stroke"><span>Full Digital Print Package</span></h2>
                        <ul class="featured">
                            <li>Sublimation printed top</li>
                            <li>3 x Sublimation printed full height walls</li>
                            <li>Unlimited print coverage!</li>
                            <li>Great value discounted package deal</li>
                            <li>Complete with Roller Bag</li>
                            <li>Tie down ropes and stakes kit</li>
                            <li>2 or 3 year warranty depending on frame choice</li>
                            <li class="thumb-li">600 Denier PVC backed materials</li>
                            <li class="thumb-li">100% Waterproof &amp; Flameproof</li>
                            <li class="thumb-li">12 month UV anti-fade guarantee<br /><br /></li>
                            <li class="thumb-li"><span style="font-size: medium;"><a href="/full-digital-package.html" target="_self">Click here for more information</a></span></li>
                        </ul>
                    </div>

                        <div class="col-md-7 tab-pane active" id="full-10-10"><a href="http://www.instantpromotionusa.com/full-digital-package.html" target="_self"><img class="img-responsive" src="{{skin url='images/packages/full-digital-print.jpg'}}" alt="" /></a></div>

                </div>
            </div>
            <div id="trader-b" class="tab-pane fade">
                <div class="row">

                    <div class="col-md-5">
                        <h2 class="top-m-0 header-stroke"><span>Trader Digital Package<br /></span></h2>
                        <ul class="featured">
                            <li>Sublimation printed top</li>
                            <li>1 x Sublimation printed full height wall</li>
                            <li>2 x Sublimation single sided half walls</li>
                            <li>1 x 6ft Printed Table Cover</li>
                            <li>Unlimited print coverage!</li>
                            <li>Great value discounted package deal</li>
                            <li>Complete with Roller Bag</li>
                            <li>Tie down ropes and stakes kit</li>
                            <li>2 or 3 year warranty depending on frame choice</li>
                            <li class="thumb-li">600 Denier PVC backed materials</li>
                            <li class="thumb-li">100% Waterproof &amp; Flameproof</li>
                            <li class="thumb-li">12 month UV anti-fade guarantee<br /><br /></li>
                            <li class="thumb-li"><span style="font-size: medium;"><a href="/trader-digital-package.html" target="_self">Click here for more information</a></span></li>
                        </ul>
                    </div>
                        <div class="col-md-7 tab-pane active" id="trader-b-10-10"><a href="/trader-digital-package.html"><img class="img-responsive" src="{{skin url='images/packages/trader-b.jpg'}}" alt="" /></a></div>
                </div>
            </div>
            <div id="sport-digital-extreme" class="tab-pane fade">
                <div class="row">

                    <div class="col-md-5">
                        <h2 class="top-m-0 header-stroke"><span>Sport Digital Package</span></h2>
                        <ul class="featured">
                            <li>Sublimation printed top</li>
                            <li>1 x Sublimation printed full height wall</li>
                            <li>2 x Sublimation single sided half walls</li>
                            <li>Unlimited print coverage!</li>
                            <li>Great value discounted package deal</li>
                            <li>Complete with Roller Bag</li>
                            <li>Tie down ropes and stakes kit</li>
                            <li>2 or 3 year warranty depending on frame choice</li>
                            <li class="thumb-li">600 Denier PVC backed materials</li>
                            <li class="thumb-li">100% Waterproof &amp; Flameproof</li>
                            <li class="thumb-li">12 month UV anti-fade guarantee<br /><br /></li>
                            <li class="thumb-li"><span style="font-size: medium;"><a href="/sport-digital-package.html" target="_self">Click here for more information</a></span></li>
                        </ul>
                    </div>
                        <div class="col-md-7 tab-pane active" id="sport-10-10"><a href="/sport-digital-package.html" target="_self"><img class="img-responsive" src="{{skin url='images/packages/sport-digital.jpg'}}" alt="" /></a></div>
                </div>
            </div>
            <div id="expo-digital" class="tab-pane fade">
                <div class="row">
                    <div class="col-md-5">
                        <h2 class="top-m-0 header-stroke"><span>Expo Digital Package</span></h2>
                        <ul class="featured">
                            <li>Sublimation printed top</li>
                            <li>1 x Sublimation printed full height wall</li>
                            <li>2 x Sublimation single sided half walls</li>
                            <li>Custom Printed Pop Up Counter</li>
                            <li>Unlimited print coverage!</li>
                            <li>Great value discounted package deal</li>
                            <li>Complete with Roller Bag</li>
                            <li>Tie down ropes and stakes kit</li>
                            <li>2 or 3 year warranty depending on frame choice</li>
                            <li class="thumb-li">600 Denier PVC backed materials</li>
                            <li class="thumb-li">100% Waterproof &amp; Flameproof</li>
                            <li class="thumb-li">12 month UV anti-fade guarantee<br /><br /></li>
                            <li class="thumb-li"><span style="font-size: medium;"><a href="/expo-digital-package.html" target="_self">Click here for more information</a></span></li>
                        </ul>
                    </div>
                        <div class="col-md-7 tab-pane active" id="expo-10-10"><a href="/expo-digital-package.html" target="_self"><img class="img-responsive" src="{{skin url='images/packages/expo-digital.jpg'}}" alt="" /></a></div>
                </div>
            </div>
            <div id="instant-event" class="tab-pane fade">
                <div class="row">
                    <div class="col-md-5">
                        <h2 class="top-m-0 header-stroke"><span>Instant Event Package</span></h2>
                        <ul class="featured">
                            <li>Sublimation printed top (unlimited print!)</li>
                            <li>1 x Back wall with single sided print</li>
                            <li>2 x Single sided print half walls &amp; support bars</li>
                            <li>2 x 11.5ft Feather Flag kits with bases</li>
                            <li>Unlimited print coverage!</li>
                            <li>Great value discounted package deal</li>
                            <li>Complete with Roller Bag</li>
                            <li>Tie down ropes and stakes kit</li>
                            <li>2 or 3 year warranty depending on frame choice</li>
                            <li class="thumb-li">600 Denier PVC backed materials</li>
                            <li class="thumb-li">100% Waterproof &amp; Flameproof</li>
                            <li class="thumb-li">12 month UV anti-fade guarantee<br /><br /><strong></strong></li>
                            <li class="thumb-li"><span style="font-size: medium;"><a href="/instant-canopies/instant-event-package.html" target="_self">Click here for more information</a></span></li>
                        </ul>
                    </div>
                        <div class="col-md-7 tab-pane active" id="instant-event-10-10"><a href="/instant-canopies/instant-event-package.html" target="_self"><img class="img-responsive" src="{{skin url='images/packages/instant-event.jpg'}}" alt="" /></a></div>
                </div>
            </div>
            <div id="instant-exhibition" class="tab-pane fade">
                <div class="row">
                    <div class="col-md-5">
                        <h2 class="top-m-0 header-stroke"><span>Instant Expo Package</span></h2>
                        <ul class="featured">
                            <li>Sublimation printed top (unlimited print!)</li>
                            <li>1 x Back wall with single sided print</li>
                            <li>2 x Single sided print side walls</li>
                            <li>2 x 11.5ft Feather Flag kits with bases</li>
                            <li>Printed Pop Up Counter</li>
                            <li>Unlimited print coverage!</li>
                            <li>Great value discounted package deal</li>
                            <li>Complete with Roller Bag</li>
                            <li>Tie down ropes and stakes kit</li>
                            <li>2 or 3 year warranty depending on frame choice</li>
                            <li class="thumb-li">600 Denier PVC backed materials</li>
                            <li class="thumb-li">100% Waterproof &amp; Flameproof</li>
                            <li class="thumb-li">12 month UV anti-fade guarantee<br /><br /><strong></strong></li>
                            <li class="thumb-li"><span style="font-size: medium;"><a href="/instant-canopies/instant-expo-package.html" target="_self">Click here for more information</a></span></li>
                        </ul>
                    </div>
                        <div class="col-md-7 tab-pane active" id="instant-exhibition-10-10"><a href="/instant-canopies/instant-expo-package.html" target="_self"><img class="img-responsive" src="{{skin url='images/packages/instant-exhibition.jpg'}}" alt="" /></a></div>
                </div>
            </div>
            <div id="instant-trader" class="tab-pane fade">
                <div class="row">
                    <div class="col-md-5">
                        <h2 class="top-m-0 header-stroke"><span>Instant Trader Package</span></h2>
                        <ul class="featured">
                            <li>Sublimation printed top (unlimited print!)</li>
                            <li>1 x Back wall with single sided print</li>
                            <li>2 x Single sided print side walls</li>
                            <li>2 x 8ft Teadrop Flags with frame brackets</li>
                            <li>6ft Wide loose fitting printed table throw</li>
                            <li>Unlimited print coverage!</li>
                            <li>Great value discounted package deal</li>
                            <li>Complete with Roller Bag</li>
                            <li>Tie down ropes and stakes kit</li>
                            <li>2 or 3 year warranty depending on frame choice</li>
                            <li class="thumb-li">600 Denier PVC backed materials</li>
                            <li class="thumb-li">100% Waterproof &amp; Flameproof</li>
                            <li class="thumb-li">12 month UV anti-fade guarantee<strong>.<br /><br /><a href="/instant-canopies/instant-trader-package.html" target="_self"><span style="font-size: medium;">Click here for more information</span></a><br /></strong></li>
                        </ul>
                    </div>
                        <div class="col-md-7 tab-pane active" id="instant-trader-10-10"><a href="http://www.instantpromotionusa.com/instant-canopies/instant-trader-package.html" target="_self"><img class="img-responsive" src="{{skin url='images/packages/instant-trader.jpg'}}" alt="" /></a></div>
                </div>
            </div>

        </div>
    </div>
</div>
<!--End Row-->