<?php
/**
 * @category    MT
 * @package     MT_Widget
 * @copyright   Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php
$attributes = $this->getAttibuteOptions();
$id         = $this->getConfig('id');
$column     = $this->getConfig('column');
$scroll     = $this->getConfig('scroll');
$title      = $this->getConfig('widget_title');
?>
<?php if ($scroll == 1):?>
    <script type="text/javascript">
        $mt(document).ready(function(){
            var itemsCount = getFlexSliderItemWidth('<?php echo $id?>', <?php echo $this->getConfig('responsive')?>, 'column');
            $mt('#<?php echo $id?>').flexslider({
                namespace: '<?php echo $this->getConfig('namespace')?>',
                slideshow: <?php echo $this->getConfig('autoplay')?>,
				controlsContainer: "#nav-wrapper-<?php echo $id ?>",
                slideshowSpeed: <?php echo $this->getConfig('speed')?>,
                animationLoop: <?php echo $this->getConfig('loop')?>,
                controlNav: <?php echo $this->getConfig('paging')?>,
                animation: "slide",
                itemWidth: getFlexSliderItemWidth('<?php echo $id?>', <?php echo $this->getConfig('responsive')?>, 'width'),
                itemMargin: <?php echo $this->getConfig('margin')?>,
                minItems: itemsCount,
                maxItems: itemsCount,
                selector: ".slides > .slide",
                onResize: function(slider){
                    var itemsCount = getFlexSliderItemWidth('<?php echo $id?>', <?php echo $this->getConfig('responsive')?>, 'column');
                    slider.vars.minItems = itemsCount;
                    slider.vars.maxItems = itemsCount;
                }
            });
        });
    </script>
<?php endif ?>
<div class="slider-attribute-wrapper<?php echo $scroll==1 ? ' flexslider' : ''?>" id="<?php echo $id ?>">
    <div class="show-grid">
	    <div class="main-heading-attribute">
		   <div class="heading-wrapper-title">
				<?php if ($title):?>
				   <h3><?php echo $title?></h3>
				<?php endif ?>
			</div>
		</div>
		<div id="nav-wrapper-<?php echo $id ?>" class="nav-wrapper pull-right">&nbsp;</div>
	</div>
	<div class="col-lg-12" style="clear:both;">
	   <!--<div class="title-divider"><span>&nbsp;</span></div>-->
	</div>
    <ul class="slides">
        <?php foreach ($attributes as $attribute): ?>
            <li class="slide">
                <a href="<?php echo $attribute['link'] ?>" title="<?php echo Mage::helper('mtwidget')->__('%s', $attribute['label']) ?>">
                    <img class="img-responsive" src="<?php echo strpos($attribute['image'], 'http') === 0 ? $attribute['image'] : Mage::getBaseUrl('media') . $attribute['image'] ?>" alt="<?php echo $attribute['label'] ?>" />
                </a>
            </li>
        <?php endforeach ?>
    </ul>
</div>
