<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     MT
 * @package      MT_Widget
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       MagentoThemes.net
 * @email        support@magentothemes.net
 * ------------------------------------------------------------------------------
 *
 */
?>
<?php
/**
 * @see MT_Widget_Block_Widget
 */
?>
<?php
/* @var $this MT_Widget_Block_Widget */
$_productCollection = $this->getLoadedProductCollection();
$_helper            = $this->helper('catalog/output');
$_collectionSize    = $_productCollection->count();
$_rowCount          = $this->getConfig('row');
$_scroll            = $this->getConfig('scroll');
$_column            = $this->getConfig('column');
$_columnCount       = $_scroll==1 ? $this->getConfig('limit') : $_column;
$_id                = $this->getConfig('id');
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <?php if ($_scroll == 1):?>
        <script type="text/javascript" src="<?php echo Mage::getBaseUrl('js')?>mt/extensions/$mt/$mt-1.9.1.min.js"></script>
        <!--script type="text/javascript" src="<?php echo Mage::getBaseUrl('js')?>mt/extensions/$mt/plugins/$mt.easing.min.js"></script-->
        <script type="text/javascript" src="<?php echo Mage::getBaseUrl('js')?>mt/extensions/$mt/plugins/flexslider/$mt.flexslider.js"></script>
        <script type="text/javascript" src="<?php echo Mage::getBaseUrl('js')?>mt/widget/frontend.js"></script>
        <script type="text/javascript">
            $mt(document).ready(function(){
                $mt('#<?php echo $_id?>').flexslider({
                    namespace: '<?php echo $this->getConfig('namespace')?>',
                    slideshow: <?php echo $this->getConfig('autoplay')?>,
                    slideshowSpeed: <?php echo $this->getConfig('speed')?>,
                    animationLoop: <?php echo $this->getConfig('loop')?>,
                    controlNav: <?php echo $this->getConfig('paging')?>,
                    animation: "slide",
                    itemWidth: getFlexSliderItemWidth('<?php echo $_id?>', <?php echo $_column?>),
                    itemMargin: 0,
                    minItems: 1,
                    maxItems: <?php echo $_column ?>,
                    selector: ".slides > .slide"
                });
            });
        </script>
    <?php endif ?>
    <div class="category-products<?php echo $_scroll == 1 ? ' flexslider' : '' ?>" id="<?php echo $_scroll == 1 ? $_id : '' ?>">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
            <?php if ($_scroll==1 && $_rowCount>1 && $i==0):?>
                <div class="slides">
            <?php endif ?>
            <?php if ($_scroll==1 && $_rowCount>1 && $i%$_rowCount==0):?>
                <!--start slide--><div class="slide">
            <?php endif ?>
            <?php if ($i%$_columnCount==0 || ($_scroll==1 && $_rowCount>1 && $i%$_rowCount==0)): ?>
                <ul class="products-grid<?php echo $_scroll==1 && $_rowCount==1 ? ' slides' : ''?>">
            <?php endif ?>
            <li class="slide item<?php if($i%$_columnCount==0 || ($_scroll==1 && $_rowCount>1 && $i%$_column==0)): ?> first<?php elseif(($i+1)%$_columnCount==0 || ($_scroll==1 && $_rowCount>1 && ($i+1)%$_column==0)): ?> last<?php endif; ?>">
                <?php $i++ ?>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
					<img class="lazy" data-src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>"  alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a>
				<h2 class="product-name">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                        <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                    </a>
                </h2>
                <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                            <span><span><?php echo $this->__('Add to Cart') ?></span></span>
                        </button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li>
                                <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist">
                                    <?php echo $this->__('Add to Wishlist') ?>
                                </a>
                            </li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li>
                                <span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </li>
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize || ($_scroll==1 && $_rowCount>1 && $i%$_rowCount==0)): ?>
                </ul>
            <?php endif ?>
            <?php if ($_scroll==1 && $_rowCount>1 && ($i%$_rowCount==0 || $i==$_collectionSize)):?>
                </div><!--end slide-->
            <?php endif ?>
            <?php if ($_scroll==1 && $_rowCount>1 && $i==$_collectionSize):?>
                </div>
            <?php endif ?>
        <?php endforeach ?>
    </div>
<?php endif; ?>