<?php
/**
 * @category    MT
 * @package     MT_Widget
 * @copyright   Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<iframe src="//player.vimeo.com/video/50406912" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> 
<p>
  <a href="http://vimeo.com/50406912">When Outrageous Was Possible</a> from <a href="http://vimeo.com/petroli">Petrolicious</a> on <a href="https://vimeo.com">Vimeo</a>.
</p>