<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     MT
 * @package      MT_Themes
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       MagentoThemes.net
 * @email        support@magentothemes.net
 * ------------------------------------------------------------------------------
 *
 */
?> 
<script type="text/javascript">
	(function($){
		<?php if (Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxwishlist')) : ?>
		$('.block-wishlist #wishlist-sidebar a').on('click', function(){
			if (confirm($(this).attr('data-confirm'))) {
				removetowishlist($(this));
			} 
			return false;
		});
		$('.add-to-links a.link-wishlist').on('click', function(){
			addtowishlist($(this));
			return false;
		});  
		if($('.product-view').length>0){
			productAddToCartForm.submitLight = function(button, url){
				return false; 
			}.bind(productAddToCartForm);
		}
		<?php endif;?>
		<?php if (Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxcompare')) : ?>
		$('.add-to-links a.link-compare').on('click', function(){
			addtocompare($(this)); 
			return false;
		});
		$('.block-compare #compare-items a, .block-top-compare a.btn-remove').on('click', function(){
			if (confirm($(this).attr('data-confirm'))) {
				removecompare($(this));
			} 
			return false;
		});   
		$('.block-compare .clearall a, .block-compare .actions a, .block-top-compare .clearall a').on('click', function(){
			if (confirm($(this).attr('data-confirm'))) {
				clearallcompare($(this));
			} 
			return false;
		}); 
		<?php endif;?>
	})($mt);
</script>